backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/assets
public_folder: /assets

publish_mode: editorial_workflow

collections:
  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files: 
      - file: "content/settings/general.md"
        label: "Site Settings"
        name: "general"
        fields:
          - {label: "Global Title", name: "title", widget: "string"}
          - {label: "Global SubTitle", name: "subtitle", widget: "string"}
          - {label: "Menu", name: "menu", widget: "list", fields:[{label: Text, name: text, widget: string},{label: URL, name: text, widget: string}]}
          - {label: "Contact Settings", name: "contact", widget: object, fields:[{label: "Address", name: "address", widget: "text"}, {label: "Email", name: "email", widget: "string"}, {label: "Phone", name: "phone", widget: "string"}]}
          - {label: "Footer", name: "footer", widget: object, fields:[{label: "Copyright", name: "copyright", widget: "string"}, {label: "Footer Links", name: "footerlinks", widget: "list", fields: [{label: "Link Text", name: "linktext", widget: "string"},{label: "Link URL", name: "linkurl", widget: "string"}]}, {label: "Social Icons", name: "socialicons", widget: "list", fields: [{label: "Icon Class", name: "iconclass", widget: "string"},{label: "Icon URL", name: "iconurl", widget: "string"}]}]}

  - name: "fixedpages"
    label: "Fixed Pages"
    files:
      - file: "content/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: Banner, name: banner, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: SubHeading, name: subheading, widget: string}, {label: BackgroundImage, name: bgimage, widget: image}]}
          - {label: Services, name: services, widget: list, fields: [{label: Heading, name: heading, widget: string}, {label: SubHeading, name: subheading, widget: string}, {label: Image, name: image, widget: image}, {label: LinkText, name: linktext, widget: string}, {label: LinkURL, name: linkurl, widget: string}] }
          - {label: "Intro Section", name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}]}

  - name: "service"
    label: "Service"
    folder: "content/service"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "service-detail"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Image", name: "image", widget: image}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Sections", name: sections, widget: list, fields: [{label: Title, name: title, widget: string}, {label: SubTitle, name: subtitle, widget: string},{label: Image, name: image, widget: image}, {label: Description, name: description, widget: text}]}

  - name: "autopages"
    label: "Automatic Pages"
    folder: "content/autopage"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "generic-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: Image, name: image, widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
